# This assumes binaries are present, see COPY directive.

FROM alpine AS chmodder
ARG TARGETARCH
COPY /artifacts/binaries-$TARGETARCH/proxy /app/
RUN chmod +x /app/*

FROM gcr.io/distroless/cc
#ARG COMPONENT
#ARG TARGETARCH
#COPY /artifacts/binaries-$TARGETARCH/$COMPONENT /usr/local/bin/
COPY --from=chmodder /app/* /usr/local/bin/
#ENTRYPOINT [ "/usr/local/bin/$COMPONENT" ]
ENTRYPOINT [ "/usr/local/bin/proxy" ]

