FROM rust:bullseye AS builder
WORKDIR /usr/src/app
COPY . .

RUN cargo build --bin broker --release

FROM gcr.io/distroless/cc
COPY --from=builder /usr/src/app/target/release/broker /usr/local/bin/
ENTRYPOINT [ "/usr/local/bin/broker" ]
