# This assumes binaries are present, see COPY directive.

FROM gcr.io/distroless/cc
#ARG COMPONENT
ARG TARGETARCH
#COPY /artifacts/binaries-$TARGETARCH/$COMPONENT /usr/local/bin/
COPY /artifacts/binaries-$TARGETARCH/proxy /usr/local/bin/
#ENTRYPOINT [ "/usr/local/bin/$COMPONENT" ]
ENTRYPOINT [ "/usr/local/bin/proxy" ]
