FROM rust:bullseye AS builder
WORKDIR /usr/src/app
COPY . .
RUN cargo build --bin broker --release

FROM gcr.io/distroless/cc
COPY --from=builder /usr/src/app/target/release/broker /usr/local/bin/
COPY --from=builder /usr/src/app/config /etc/samply/beam
ENTRYPOINT [ "/usr/local/bin/broker" ]
