# This assumes that the binary is available at path "proxy"

#Distroless images have no chmod command
FROM alpine AS chmodder
COPY artifacts/proxy /
RUN chmod +x /proxy

FROM gcr.io/distroless/cc
COPY --from=chmodder /proxy /
ENTRYPOINT [ "/proxy" ]
