# This assumes that the binary is available at path "broker"

FROM debian:bullseye-slim
COPY artifacts/broker /usr/local/bin/
RUN chmod +x /usr/local/bin/broker
ENTRYPOINT [ "/usr/local/bin/broker" ]
