# This assumes binaries are present, see COPY directive.

ARG IMGNAME=gcr.io/distroless/cc

FROM alpine AS chmodder
ARG FEATURE
ARG TARGETARCH
COPY /artifacts/binaries-$TARGETARCH$FEATURE/broker /app/
RUN chmod +x /app/*

FROM ${IMGNAME}
#ARG COMPONENT
#ARG TARGETARCH
#COPY /artifacts/binaries-$TARGETARCH/$COMPONENT /usr/local/bin/
COPY --from=chmodder /app/* /usr/local/bin/
#ENTRYPOINT [ "/usr/local/bin/$COMPONENT" ]
ENTRYPOINT [ "/usr/local/bin/broker" ]

